// ตั้งค่า DeptFlow — แก้ไฟล์นี้ได้ ห้ามใส่ชื่อหรือรหัสพนักงานจริง

// ชื่อแผนกที่ให้เลือก (ใช้เป็นชื่อไฟล์ด้วย) พิมพ์ชื่อใหม่ในแอปได้เสมอ
export const DEPARTMENTS = [
  "DRY-DryFood",
  "FSH-Butchery",
  "FSH-Seafood",
  "FSH-Produce",
  "FSH-Delica",
  "FSH-Bakery",
  "FSH-Perishable",
  "FSH-Bakery&Delica",
  "FSH-Butchery&SeaFood",
  "NFD-NonFood",
  "SPR-LossPrevention",
  "SPR-Maintenance",
  "SPR-CustomerExperience",
  "SPR-Omnichannel",
  "SPR-Omnichannel-PickPa",
];

// กรอบภาพหัวเอกสารที่แสดงให้ดู [ซ้าย, บน, ขวา, ล่าง] เป็นสัดส่วนของหน้า
export const HEADER_BOX = [0.0, 0.045, 0.8, 0.125];

// กรอบช่อง "ชื่อหน่วยงาน" ที่ใช้เทียบภาพเพื่อจัดกลุ่มแผนกอัตโนมัติ (ไม่อ่านตัวหนังสือ)
// ต้องครอบเฉพาะชื่อหน่วยงาน ห้ามครอบชื่อหรือรหัสพนักงาน
export const DEPT_BOX = [0.6, 0.083, 0.82, 0.097];

// ลายเส้นภาพชื่อหน่วยงานที่รู้จักล่วงหน้า [{ name, sig }] แอปใช้ใส่ชื่อแผนกให้อัตโนมัติ
// - เป็นภาพขาวดำ 200x12 ของ "ชื่อหน่วยงาน" เท่านั้น ไม่มีชื่อหรือรหัสพนักงาน
// - ถ้าชื่อหน่วยงานในรายงานเปลี่ยน แอปจะให้ตั้งชื่อกลุ่มใหม่ แล้วจำเพิ่มในเครื่องเอง
export const KNOWN_SIGNATURES = [
  { name: "DRY-DryFood", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAjx9B4AMA8AMAQAAAAAAAAAAQYNiQsWPjwJghYzAMADAAAGAAAAAAAAAAAGDYsINnw8iwMR4w7Gcw8Pl8AAAAAAAAAADg3x+8bcPAsB8MN2wk8BmNYgAAAAAAAAAAYNiQoHHDwLAxCDBsPDAYjWIAAAAAAAAAEGDYsL9xw8ifYQjwZxgw8Pl8AAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAA" },
  { name: "FSH-Butchery", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ+AEAEAAAAAAAAAAAAAAQYNiQsWPjwEDIEBgDDBAAAAAAAAAAAAAAAGDYsINnw8jAwRiYmd33+X4EAAAAAAAAAADg3x+8bcPAD8+f+5ttEP3GAgAAAAAAAAAAYNiQoHHDwEDYEBibbRCNhgMAAAAAAAAAEGDYsL9xw8jAzxD4+9kX+YYBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAA" },
  { name: "FSH-Seafood", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ8AEADACAAAAAAAAAAAAQYNiQsWPjwEDIEBgDAAYAwAAAAAAAAAAAAGDYsINnw8jAwRg48Pzu8/gAAAAAAAAAAADg3x+8bcPAD8+fw/nhNgrNAAAAAAAAAAAAYNiQoHHDwEDYEAga3DYKzQAAAAAAAAAAEGDYsL9xw8jAzxD4++3m8/kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "FSH-Produce", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ+AEACAAAAAAAAAAAAAAQYNiQsWPjwEDIEBgDAAwAAAAAAAAAAAAAAGDYsINnw8jAwRgYe59v9vkAAAAAAAAAAADg3x+8bcPAD8+f+5nRbBb8AAAAAAAAAAAAYNiQoHHDwEDYEBiY0GwWjAAAAAAAAAAAEGDYsL9xw8jAzxAYmJ/v9/kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "FSH-Delica", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ+AFIAAAAAAAAAAAAAAAQYNiQsWPjwEDIEBgDCAAAAAAAAAAAAAAAAGDYsINnw8jAwRgY9kmeDwAAAAAAAAAAAADg3x+8bcPAD8+fG/ZLAw4AAAAAAAAAAAAAYNiQoHHDwEDYEBgWScMNAAAAAAAAAAAAEGDYsL9xw8jAzxD480n+DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "FSH-Bakery", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ+AEMAAAAAAAAAAAAAAAQYNiQsWPjwEDIEBgDDAAAAAAAAAAAAAAAAGDYsINnw8jAwRiY+W2+nwEAAAAAAAAAAADg3x+8bcPAD8+f+8E9v9EAAAAAAAAAAAAAYNiQoHHDwEDYEBibPYNxAAAAAAAAAAAAEGDYsL9xw8jAzxD4+02+YQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAA" },
  { name: "FSH-Perishable", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ+AHAgAAgEAAAAAAAAAAQYNiQsWPjwEDIEBgDAIABIBAAAAAAAAAAAGDYsINnw8jAwRgY8/y+z++TDwAAAAAAAADg3x+8bcPAD8+f+/nNjhlu1g8AAAAAAAAAYNiQoHHDwEDYEBgYzLjZLNYIAAAAAAAAEGDYsL9xw8jAzxAY+M2+2e+TDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "FSH-Bakery&Delica", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ+AEMAACAB/gAJAAAAAAQYNiQsWPjwEDIEBgDDAAAgAQMAQwAAAAAAGDYsINnw8jAwRiY+W2+n4EHDPMt3wcAAADg3x+8bcPAD8+f+8E9v9HACwz7rQEOAAAAYNiQoHHDwEDYEBibPYNxQAwMG6zBDAAAEGDYsL9xw8jAzxD4+02+YcAf/PEt3w8AAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAA" },
  { name: "FSH-Butchery&SeaFood", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAj0cQ+AEAEAAAABzAAwCAHwAQYNiQsWPjwEDIEBgDDBAAAAASYAQAgAEAAGDYsINnw8jAwRiYmd33+X4EHuDg84GBzwDg3x+8bcPAD8+f+5ttEP3GAh+A54eB32gAYNiQoHHDwEDYEBibbRCNhgNzICwwgcFoEGDYsL9xw8jAzxD4+9kX+YYBf+Dns4GBzwAAAAAAAAAAAAAAAAAAAACAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAA" },
  { name: "NFD-NonFood", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcLAkJ8fMAQAgB8AAAEAAAAAAAAQYNiQsWPjwJGBMHAEAIAAAAADAAAAAAAAAGDYsINnw8iTgSDQ5POBwe/zAwAAAAAAAADg3x+8bcPAlo/glzUWgU8oFAMAAAAAAAAAYNiQoHHDwJyBIBA3FoFAKBQDAAAAAAAAEGDYsL9xw8iYgR8Q5hOBwO/zAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "SPR-LossPrevention", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcKAj48fEAAAAPwAAAAAIAAAAAAQYNiQsWPjwNiQMBAAAACMAQAAAAYAAAAAAGDYsINnw8jBkDAQ+D4PjL1v9v0u3w8AAADg3x+8bcMA3o+fF4wOB/zMT/qNpNEMAAAAYNiQoHHDQNiAGBCMcBwMzMgbjaTRCAAAEGDYsL9xw4jfgCDw+T4fDIyP8Y0s3wwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "SPR-Maintenance", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcKAj48fMAggAAAAAAAAAAAAAAAQYNiQsWPjwNiQMDAcAIAAAAAAAAAAAAAAAGDYsINnw8jBkDBw3ifffT6fz/cBAAAAAADg3x+8bcMA3o+f1xoukfxmnGj4AwAAAAAAYNiQoHHDQNiAGJDbLJEMYpNoGAAAAAAAEGDYsL9xw4jfgCCQ2S+RfWafyPcBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "SPR-CustomerExperience", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcKAj48fwAMAAAAAAMAfAABAAAAQYNiQsWPjwNiQMDAGAAQAAABAAAAAAAAAAGDYsINnw8jBkDAQIPLu85/vwcD2+dw+nwDg3x+8bcMA3o+fFyByJBTRb8CPM/vNftEAYNiQoHHDQNiAGBAkwyUU0WBAgDOLxCLREGDYsL9xw4jfgCDg5/PtE5FvwN/2+cQ+kQAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAA" },
  { name: "SPR-Omnichannel", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcKAj48fwAMAgAABAAAABAAAAAAQYNiQsWPjwNiQMDAMAACAAQAAAAQAAAAAAGDYsINnw8jBkDAQ7D+fvJ/v9/kEAAAAAADg3x+8bcMA3o+fH2gmkYIRbjb7BQAAAAAAYNiQoHHDQNiAGBBsJpGC0W0WGwQAAAAAEGDYsL9xw4jfgCDgZyaRvNFvNvsFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
  { name: "SPR-Omnichannel-PickPa", sig: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgyBAfYcKAj48fwAMAgAABAAAABAB+BAgQYNiQsWPjwNiQMDAMAACAAQAAAAQAhgEIAGDYsINnw8jBkDAQ7D+fvJ/v9/kEAIblaQDg3x+8bcMA3o+fH2gmkYIRbjb7BQ7+NDwAYNiQoHHDQNiAGBBsJpGC0W0WGwQABjRsEGDYsL9xw4jfgCDgZyaRvNFvNvsFAAbkyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
];

// ใช้เฉพาะ PDF ที่มีข้อความ: อ่านชื่อแผนกจากส่วนบนของหน้าเพื่อเติมให้ล่วงหน้า (ไฟล์สแกนต้องเลือกเอง)
export const HEADER_AREA = 0.3;
export const DEPARTMENT_PATTERNS = [
  /(?:ชื่อ)?(?:หน่วยงาน|แผนก|ฝ่าย)\s*[:：]?\s*(.+?)(?=\s{2,}|\s*(?:รหัส|ชื่อ|ตำแหน่ง|วันที่|ประจำ|หน้า|ระหว่าง)|$)/u,
  /(?:Dept|Department)\s*[:：]?\s*(.+?)(?=\s{2,}|\s*(?:Emp|Name|Date|Page)|$)/u,
];

// เปลี่ยนชื่อที่อ่านได้ให้เป็นชื่อที่ต้องการ เช่น { "FSH-Bakery&Delica": "FSH-Bakery" }
export const ALIASES = {};
